name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed
  
  $CHANGES

categories:
  - title: '💥 Breaking'
    label: 'breaking'
  - title: '🚀 New'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title: '📄 Chore'
    label: 'chore'
  - title: '🤖 Dependency Updates'
    label: 'dependencies'


version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
