name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed
  
  $CHANGES

categories:
  - title: '💥 Breaking'
    labels: ['breaking']
  - title: '🚀 New'
    labels: ['feature']
  - title: '🐛 Bug Fixes'
    labels: ['bug']
  - title: '🧰 Maintenance'
    labels: ['maintenance']
  - title: '📄 Chore'
    labels: ['chore']
  - title: '🤖 Dependency Updates'
    labels: ['dependencies']


version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
