name: "release"

on:
    release:
        types: [published]

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: |
                  npm install
                  npm run build:action --if-present
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
